### ISSUE TITLE
Project Movement

### ISSUE THREAD

**Issue by sparsick** [georgberky/dependency-update-maven-plugin#15]
This project was moved from @helpermethod account to @georgberky account. The following things have to be done to have a clean movement:

- [x] Update repository permissions
- [x] Propose a new group ID because of Maven Central policy about [Maven coordinates](https://central.sonatype.org/publish/requirements/coordinates/)
- [x] Change SCM Entries in POM file.
- [x] URL Entry should be changed
- [x] Update POM information
- [x] Create a release with the old Maven coordinates for a clean relocation (see [Maven Guide for Relocation](https://maven.apache.org/guides/mini/guide-relocation.html)
- [x] Change package names in Java/Kotlin accordingly to groupId

**Comment by sparsick** [comment]
@helpermethod We need you help to finish the movement cleanly. Could you please create a release with your old Maven coordinates for a clean relocation? See also [Maven Guide for Relocation](https://maven.apache.org/guides/mini/guide-relocation.html). 

We think your relocation POM should look like the following one:

```xml
    <project>
      <modelVersion>4.0.0</modelVersion>
      <groupId>com.github.helpermethod</groupId>
      <artifactId>dependency-update-maven-plugin</artifactId>
      <version>0.7.0</version>
      <distributionManagement>
        <relocation>
          <groupId>io.github.georgberky.maven.plugins.depsupdate</groupId>
        </relocation>
      </distributionManagement>
    </project>
```

**Comment by helpermethod** [comment]
@sparsick Sure, I'll give it a go!

**Comment by helpermethod** [comment]
Hm, not sure what happened. Created a relocation release, and it disappeared from the Nexus Staging repository.

**Comment by helpermethod** [comment]
Looking good!

![image](https://user-images.githubusercontent.com/1562019/118774431-1e650f00-b886-11eb-8aa9-3efd5dd1a93b.png)

**Comment by sparsick** [comment]
@helpermethod Thank you very much !!! Looks great. We hope that we can make the 0.7.0 release next week.

**Comment by sparsick** [comment]
We release it :tada: :tada:
