### ISSUE TITLE
Implement a native git provider

### ISSUE THREAD

**Issue by helpermethod** [georgberky/dependency-update-maven-plugin#9]
The project currently uses `jgit` for creating branches, committing modifications, pushing refs, etc... . 

While `jgit` offers some benefits (Java-based DSL, does not require a native git client) it requires extensive setup for authenticating against a remote repository, which may be acceptable in Docker-based CI environments but not so in non-Docker based environments (Jenkins without Docker agent, local dev machine).

The goal of this ticket is to implement a git provider which uses the native git executable if present.

**Comment by sparsick** [comment]
Hi @helpermethod, if you are interested, @georgberky and me could contribute a proposal of an implementation for this feature.

**Comment by helpermethod** [comment]
That would be awesome!

**Comment by helpermethod** [comment]
Hi @sparsick,

because your commits already improve `dependency-update-maven-plugin` by a large margin, would you like to do a first PR?

The concrete implementation of the `NativeGitProvider` (or whatever you may call it) could be done in a separate PR.

What do you think?

**Comment by helpermethod** [comment]
BTW I've created a Slack channel to discuss ideas, further development, tooling and so on

https://join.slack.com/t/dependencyupd-pfm5382/shared_invite/zt-d34ieqlj-qk9T6YLmtYwaxFAAiY34kA

I will also add a badge to the `README.me` if time permits.

**Comment by sparsick** [comment]
Hi @helpermethod 

> because your commits already improve dependency-update-maven-plugin by a large margin, 
> would you like to do a first PR?

It is a good idea. Let me change the PR title and description and then you can go for it. @georgberky and I want to continue on Friday with the implementation.

**Comment by sparsick** [comment]
As disussed on slack, the native git provider would be default, but you can make it configurable. 

```xml
<configuration>
        <gitProvider>native</gitProvider>
</configuration>
```

We will have two option for `gitProvider`: `native` or `jgit`
